Update 38592 Vaeshok.sql
ACEmulator/ACE-World-16PY-Patches pull request #1054
Opened 2021-09-10 23:06 UTC by Fire-Chimp

upped the al on body parts, adjusted resists

2021-09-10 23:47 UTC, ziang4891 requested changes
Changed skill levels are way too high.  The attributes will push the effective skill levels outside of the players range of ability to counter.  Also, the CreateList has been zeroed out by the change

2021-09-11 01:26 UTC, Fire-Chimp commented
I was told that if i typed in a number into the skill final level that is what the mobs skill is.

2021-09-11 21:56 UTC, ziang4891 approved these changes

2021-09-12 03:19 UTC, DridsGhost submitted a review, later dismissed

2021-09-12 04:31 UTC, merged