Update Mage Academy
ACEmulator/ACE-World-16PY-Patches pull request #1496
Opened 2023-03-11 21:47 UTC by TectonicRifts

Updates the Mage Academy quest, including Burial Temple and Mage Academy dungeons with the new high level retail spawns.

http://acpedia.org/wiki/The_Mage_Academy

Adds Lady Jaria's Wand, and updates 05763 Tazal al-Ashfai with new rewards for the wand, and Black Gem from the Burial Temple.

Burial Temple now has a 150+ restriction like in retail.

Adds door, lever and surface portal in the new section of Burial Temple, used to access the Warded Portal during the seasonal Undead Attack on Al-Jalima quest. This DOES NOT add the Warded Portal itself.

2023-03-17 21:05 UTC, OptimShi requested changes
Go ahead and add `Contract for Mage Academy` (48727) to "Complete" this.

- TN Barkeep wcid 42801 already has the 48727 wcid in his inventory for sale, so no worry about setting that.

On questflag_repeat_time: TrophyMageAcademy_1110 (whether this is on the pickup of the wand or on the turn in is up to you... The name sounds like it's on the wand pickup, but I could go either way here)
Probably reduce the contract "questflag_started" `mageacademykey` to 20 hours, as well.

2023-03-17 21:05 UTC, OptimShi commented on Database/Patches/9 WeenieDefaults/Creature/Human/05763 Tazal al-Ashfai.sql
He got some vassal XP somewhere along the line and should be level 132

2023-03-18 23:31 UTC, ziang4891 approved these changes

2023-03-20 23:09 UTC, OptimShi approved these changes

2023-03-22 01:30 UTC, merged