Son of pooky quest+white rabbit update
ACEmulator/ACE-World-16PY-Patches pull request #600
Opened 2020-08-22 20:13 UTC by sLackeR-hub

Complete Son of Pooky quest with Quest Timer insert / Also added updated White Rabbit to drop Portal Gem and updated White Rabbit Girth to show properly.

**Need to have the lucky white rabbits foot fix PR#3139 for it to work**

2020-08-23 16:47 UTC, ziang4891 commented on Database/Patches/2006-04-ShiningRunesAndShadowedHands/9 WeenieDefaults/Creature/Rabbit/02568 White Rabbit.sql
> +
You need to take the whole file from the original location, make the updates to it, and then place it in the new location.  We don't do partial table updates.

2020-08-23 17:15 UTC, sLackeR-hub commented on Database/Patches/2006-04-ShiningRunesAndShadowedHands/9 WeenieDefaults/Creature/Rabbit/32931 Twilight Rabbit.sql
> +
Fixed and fixed color.

2020-08-23 17:26 UTC, sLackeR-hub commented on Database/Patches/2006-04-ShiningRunesAndShadowedHands/9 WeenieDefaults/Creature/Rabbit/32929 Dusk Rabbit.sql
> +VALUES (32929,  39, 1.399999976158142) /* DefaultScale */;
Fixed.

2020-08-23 17:28 UTC, sLackeR-hub commented on Database/Patches/2006-04-ShiningRunesAndShadowedHands/9 WeenieDefaults/Creature/Rabbit/32929 Dusk Rabbit.sql
> +
Removed.

2020-08-23 17:28 UTC, sLackeR-hub commented on Database/Patches/2006-04-ShiningRunesAndShadowedHands/9 WeenieDefaults/Creature/Rabbit/32929 Dusk Rabbit.sql
> +     , (32929, 133,          4) /* ShowableOnRadar - ShowAlways */;
Should be fixed.

2020-08-23 17:28 UTC, sLackeR-hub commented on Database/Patches/2006-04-ShiningRunesAndShadowedHands/9 WeenieDefaults/Creature/Rabbit/32929 Dusk Rabbit.sql
> +INSERT INTO `weenie_properties_body_part` (`object_Id`, `key`, `d_Type`, `d_Val`, `d_Var`, `base_Armor`, `armor_Vs_Slash`, `armor_Vs_Pierce`, `armor_Vs_Bludgeon`, `armor_Vs_Cold`, `armor_Vs_Fire`, `a
Fixed

2020-08-23 17:40 UTC, sLackeR-hub commented on Database/Patches/2006-04-ShiningRunesAndShadowedHands/9 WeenieDefaults/Creature/Rabbit/32930 Night Rabbit.sql
> +     , (32930,   2,         25) /* CreatureType - Rabbit */
Fixed.

2020-08-23 20:16 UTC, sLackeR-hub commented on Database/Patches/2006-04-ShiningRunesAndShadowedHands/9 WeenieDefaults/Creature/Rabbit/32932 Son of Pooky.sql
> +INSERT INTO `weenie` (`class_Id`, `class_Name`, `type`, `last_Modified`)
Fixed.

2020-08-23 20:16 UTC, ziang4891 commented on Database/Patches/2006-04-ShiningRunesAndShadowedHands/9 WeenieDefaults/Creature/Rabbit/32929 Dusk Rabbit.sql
> +     , (32929, 103,          1) /* GeneratorDestructionType - Nothing */
MaxGeneratedObjects, InitGeneratedObjects, and  GeneratorDestructionType are unnecessary

2020-08-23 20:18 UTC, ziang4891 commented on Database/Patches/2006-04-ShiningRunesAndShadowedHands/9 WeenieDefaults/Creature/Rabbit/32930 Night Rabbit.sql
> +     , (32930,   2,         25) /* CreatureType - Rabbit */
Still missing ArmorType, CombatMode, TargetingTactic, FriendType like you added to the Dusk Rabbit

2020-08-23 20:18 UTC, ziang4891 commented on Database/Patches/2006-04-ShiningRunesAndShadowedHands/9 WeenieDefaults/Creature/Rabbit/32930 Night Rabbit.sql
> +VALUES (32930,  39,     1.5) /* DefaultScale */;
Missing the rest of the floats, like you added to the Dusk Rabbit

2020-08-23 20:40 UTC, sLackeR-hub commented on Database/Patches/2006-04-ShiningRunesAndShadowedHands/Quest Insert.sql
> +DELETE FROM `quest` WHERE `id`=5000;
Fixed.

2020-08-23 20:47 UTC, sLackeR-hub commented on Database/Patches/2006-04-ShiningRunesAndShadowedHands/9 WeenieDefaults/Creature/Rabbit/32929 Dusk Rabbit.sql
> +     , (32929, 103,          1) /* GeneratorDestructionType - Nothing */
Fixed.

2020-08-23 20:49 UTC, sLackeR-hub commented on Database/Patches/2006-04-ShiningRunesAndShadowedHands/9 WeenieDefaults/Creature/Rabbit/32930 Night Rabbit.sql
> +VALUES (32930,  39,     1.5) /* DefaultScale */;
Should be fixed. Also removed PCAP location.

2020-08-24 02:34 UTC, sLackeR-hub commented on Database/Patches/2006-04-ShiningRunesAndShadowedHands/9 WeenieDefaults/Creature/Rabbit/32932 Son of Pooky.sql
> +INSERT INTO `weenie` (`class_Id`, `class_Name`, `type`, `last_Modified`)
@ziang4891 I did some updates on Critter.

2020-08-24 15:51 UTC, sLackeR-hub commented on Database/Patches/2006-04-ShiningRunesAndShadowedHands/9 WeenieDefaults/Chest/32928 Rabbit Hutch.sql
> +INSERT INTO `weenie_properties_generator` (`object_Id`, `probability`, `weenie_Class_Id`, `delay`, `init_Create`, `max_Create`, `when_Create`, `where_Create`, `stack_Size`, `palette_Id`, `shade`, `ob
@ziang4891 I believe this chest does use the generator because it has to spawn 1 of 3 items each pull, I looked at another chest that does the same. (28436 & 29385)

2020-08-24 16:44 UTC, sLackeR-hub commented on Database/Patches/2006-04-ShiningRunesAndShadowedHands/Quest Insert.sql
> +DELETE FROM `quest` WHERE `id`=5000;
Noticed a typo - Re-pushed fix

2020-08-24 17:27 UTC, ziang4891 commented on Database/Patches/2006-04-ShiningRunesAndShadowedHands/9 WeenieDefaults/Creature/Rabbit/02568 White Rabbit.sql
> +VALUES (2568, 1,  8400,  0, 0, 0.5, False) /* Create Orb of the Bunny Booty (8400) for Contain */
Needs to be the full weenie file, rather than just a partial edit/change

2020-08-24 17:29 UTC, ziang4891 commented on Database/Patches/2006-04-ShiningRunesAndShadowedHands/9 WeenieDefaults/Chest/32928 Rabbit Hutch.sql
> +INSERT INTO `weenie_properties_generator` (`object_Id`, `probability`, `weenie_Class_Id`, `delay`, `init_Create`, `max_Create`, `when_Create`, `where_Create`, `stack_Size`, `palette_Id`, `shade`, `ob
I was actually thinking something else.  However, the -1 entry should be moved to the end, the '1' entry changed to 0.99, and the 0 entry removed.

2020-08-24 17:33 UTC, ziang4891 commented on Database/Patches/2006-04-ShiningRunesAndShadowedHands/9 WeenieDefaults/Chest/32928 Rabbit Hutch.sql
> +INSERT INTO `weenie_properties_generator` (`object_Id`, `probability`, `weenie_Class_Id`, `delay`, `init_Create`, `max_Create`, `when_Create`, `where_Create`, `stack_Size`, `palette_Id`, `shade`, `ob
Ok, looks like slot groupings are in reverse order, so -1 first on the list is correct

2020-08-24 18:21 UTC, sLackeR-hub commented on Database/Patches/2006-04-ShiningRunesAndShadowedHands/9 WeenieDefaults/Creature/Rabbit/02568 White Rabbit.sql
> +VALUES (2568, 1,  8400,  0, 0, 0.5, False) /* Create Orb of the Bunny Booty (8400) for Contain */
Fixed, with original sql.

2020-09-03 17:44 UTC, LtRipley36706 commented on Database/Patches/2006-04-ShiningRunesAndShadowedHands/9 WeenieDefaults/Chest/32928 Rabbit Hutch.sql
> +     , (32928, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0) /* Generate  (0) (x0 up to max of 0) - Regenerate upon Undef - Location to (re)Generate: Undef */;
```suggestion
     , (32928, 0.99, 32935, 0, 1, 1, 2, 8, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0) /* Generate Scroll of Ring around the Rabbit (32935) (x1 up to max of 1) - Regenerate upon PickUp - Location to (re)Generate: Contain */;
```

2020-09-03 21:10 UTC, sLackeR-hub commented on Database/Patches/2006-04-ShiningRunesAndShadowedHands/9 WeenieDefaults/Chest/32928 Rabbit Hutch.sql
> +     , (32928, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0) /* Generate  (0) (x0 up to max of 0) - Regenerate upon Undef - Location to (re)Generate: Undef */;
Changed from 1 to 0.99

2020-09-04 00:11 UTC, ziang4891 commented on Database/Patches/2006-04-ShiningRunesAndShadowedHands/9 WeenieDefaults/Chest/32928 Rabbit Hutch.sql
> +     , (32928, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0) /* Generate  (0) (x0 up to max of 0) - Regenerate upon Undef - Location to (re)Generate: Undef */;
Need to remove the zero entry at the end.  The 0.99 one should be the last.

2020-09-04 04:00 UTC, LtRipley36706 requested changes

2020-09-04 04:00 UTC, LtRipley36706 commented on Database/Patches/2006-04-ShiningRunesAndShadowedHands/9 WeenieDefaults/Chest/32928 Rabbit Hutch.sql
> +     , (32928, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0) /* Generate  (0) (x0 up to max of 0) - Regenerate upon Undef - Location to (re)Generate: Undef */;
```suggestion
     , (32928, 0.99, 32935, 0, 1, 1, 2, 8, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0) /* Generate Scroll of Ring around the Rabbit (32935) (x1 up to max of 1) - Regenerate upon PickUp - Location to (re)Generate: Contain */;
```

2020-09-04 04:00 UTC, LtRipley36706 commented on Database/Patches/2006-04-ShiningRunesAndShadowedHands/9 WeenieDefaults/Chest/32928 Rabbit Hutch.sql
> +     , (32928,  86, True ) /* ChestRegenOnClose */;
```suggestion
INSERT INTO `weenie_properties_bool` (`object_Id`, `type`, `value`)
VALUES (32928,   1, True ) /* Stuck */
     , (32928,   2, False) /* Open */
     , (32928,   3, True ) /* Locked */
     , (32928,  34, False) /* DefaultOpen */
     , (32928,  35, True ) /* DefaultLocked */;
```

2020-09-04 04:00 UTC, LtRipley36706 commented on Database/Patches/2006-04-ShiningRunesAndShadowedHands/9 WeenieDefaults/Chest/32928 Rabbit Hutch.sql
> +     , (32928,  54,       2) /* UseRadius */;
```suggestion
INSERT INTO `weenie_properties_float` (`object_Id`, `type`, `value`)
VALUES (32928,  39,     0.6) /* DefaultScale */
     , (32928,  11,      60) /* ResetInterval */
     , (32928,  54,       2) /* UseRadius */
     , (32928,  41,      60) /* RegenerationInterval */;
```

2020-09-04 04:00 UTC, LtRipley36706 commented on Database/Patches/2006-04-ShiningRunesAndShadowedHands/9 WeenieDefaults/Key/32934 Rabbit Hutch Key.sql
> +     , (32934,  53,        101) /* PlacementPosition - Resting */
```suggestion
```

2020-09-04 04:00 UTC, LtRipley36706 commented on Database/Patches/2006-04-ShiningRunesAndShadowedHands/9 WeenieDefaults/Portal/71717 Son of Pooky's Den.sql
> +     , (71717, 111,          1) /* PortalBitmask - Unrestricted */
```suggestion
     , (71717, 111,         49) /* PortalBitmask - Unrestricted, NoSummon, NoRecall */
```

2020-09-04 04:00 UTC, LtRipley36706 commented on Database/Patches/2006-04-ShiningRunesAndShadowedHands/9 WeenieDefaults/Portal/71717 Son of Pooky's Den.sql
> +     , (71717,  26,          1) /* AccountRequirements - AsheronsCall_Subscription */
```suggestion
```

2020-09-04 04:00 UTC, LtRipley36706 commented on Database/Patches/2006-04-ShiningRunesAndShadowedHands/9 WeenieDefaults/Portal/71717 Son of Pooky's Den.sql
> +     , (71717,  86,         20) /* MinLevel */
```suggestion
```

2020-09-04 04:00 UTC, LtRipley36706 commented on Database/Patches/2006-04-ShiningRunesAndShadowedHands/RabbitHutchKeyPickupTimer.sql
> +VALUES ('rabbithutchkey', 1123200, -1, 'Picked up Rabbit Hutch Key', '2019-03-14 20:34:27');
```suggestion
VALUES ('rabbithutchkey', 1123200, -1, 'Picked up Rabbit Hutch Key', '2019-03-14 20:34:27');

```

2020-09-04 04:05 UTC, bobigor377 requested changes

2020-09-04 04:05 UTC, bobigor377 commented on Database/Patches/2006-04-ShiningRunesAndShadowedHands/9 WeenieDefaults/Gem/32933 Son of Pooky's Den.sql
> +VALUES (32933,  15, True ) /* LightsStatus */;
```suggestion
VALUES (32933,  22, True ) /* Inscribable */
     , (32933,  23, True ) /* DestroyOnSell */;
```

2020-09-04 04:05 UTC, bobigor377 commented on Database/Patches/2006-04-ShiningRunesAndShadowedHands/9 WeenieDefaults/Gem/32933 Son of Pooky's Den.sql
> +     , (32933,  31,      71717) /* LinkedPortalOne - Son of Pooky's Den */;
```suggestion
     , (32933,  31,      71717) /* LinkedPortalOne - Son of Pooky's Den */
     , (32933,  50,  100676404) /* IconOverlay */;
```

2020-09-04 04:05 UTC, bobigor377 commented on Database/Patches/2006-04-ShiningRunesAndShadowedHands/9 WeenieDefaults/Gem/32933 Son of Pooky's Den.sql
> +     , (32933,  18,          1) /* UiEffects - Magical */
```suggestion
```

2020-09-04 04:12 UTC, bobigor377 requested changes

2020-09-04 04:12 UTC, bobigor377 commented on Database/Patches/2006-04-ShiningRunesAndShadowedHands/9 WeenieDefaults/Gem/32933 Son of Pooky's Den.sql
> +     , (32933,   3,         82) /* PaletteTemplate - PinkPurple */
```suggestion
     , (32933,   3,         14) /* PaletteTemplate - Red */
```

2020-09-04 13:01 UTC, sLackeR-hub commented on Database/Patches/2006-04-ShiningRunesAndShadowedHands/9 WeenieDefaults/Chest/32928 Rabbit Hutch.sql
> +     , (32928, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0) /* Generate  (0) (x0 up to max of 0) - Regenerate upon Undef - Location to (re)Generate: Undef */;
Fixed.

2020-09-04 13:01 UTC, sLackeR-hub commented on Database/Patches/2006-04-ShiningRunesAndShadowedHands/9 WeenieDefaults/Chest/32928 Rabbit Hutch.sql
> +     , (32928,  86, True ) /* ChestRegenOnClose */;
Fixed.

2020-09-04 13:02 UTC, sLackeR-hub commented on Database/Patches/2006-04-ShiningRunesAndShadowedHands/9 WeenieDefaults/Chest/32928 Rabbit Hutch.sql
> +     , (32928,  54,       2) /* UseRadius */;
Fixed.

2020-09-04 13:03 UTC, sLackeR-hub commented on Database/Patches/2006-04-ShiningRunesAndShadowedHands/9 WeenieDefaults/Key/32934 Rabbit Hutch Key.sql
> +     , (32934,  53,        101) /* PlacementPosition - Resting */
Removed.

2020-09-04 13:07 UTC, sLackeR-hub commented on Database/Patches/2006-04-ShiningRunesAndShadowedHands/9 WeenieDefaults/Portal/71717 Son of Pooky's Den.sql
> +     , (71717, 111,          1) /* PortalBitmask - Unrestricted */
Fixed on WCID 71866.

2020-09-04 13:07 UTC, sLackeR-hub commented on Database/Patches/2006-04-ShiningRunesAndShadowedHands/9 WeenieDefaults/Portal/71717 Son of Pooky's Den.sql
> +     , (71717,  26,          1) /* AccountRequirements - AsheronsCall_Subscription */
Fixed on WCID 71866.

2020-09-04 13:07 UTC, sLackeR-hub commented on Database/Patches/2006-04-ShiningRunesAndShadowedHands/9 WeenieDefaults/Portal/71717 Son of Pooky's Den.sql
> +     , (71717,  86,         20) /* MinLevel */
Fixed on WCID 71866.

2020-09-04 13:11 UTC, sLackeR-hub commented on Database/Patches/2006-04-ShiningRunesAndShadowedHands/RabbitHutchKeyPickupTimer.sql
> +VALUES ('rabbithutchkey', 1123200, -1, 'Picked up Rabbit Hutch Key', '2019-03-14 20:34:27');
Added Line before and after.

2020-09-04 13:14 UTC, sLackeR-hub commented on Database/Patches/2006-04-ShiningRunesAndShadowedHands/9 WeenieDefaults/Gem/32933 Son of Pooky's Den.sql
> +VALUES (32933,  15, True ) /* LightsStatus */;
Fixed.

2020-09-04 13:14 UTC, sLackeR-hub commented on Database/Patches/2006-04-ShiningRunesAndShadowedHands/9 WeenieDefaults/Gem/32933 Son of Pooky's Den.sql
> +     , (32933,  31,      71717) /* LinkedPortalOne - Son of Pooky's Den */;
Fixed

2020-09-04 13:14 UTC, sLackeR-hub commented on Database/Patches/2006-04-ShiningRunesAndShadowedHands/9 WeenieDefaults/Gem/32933 Son of Pooky's Den.sql
> +     , (32933,  18,          1) /* UiEffects - Magical */
Removed.

2020-09-04 13:15 UTC, sLackeR-hub commented on Database/Patches/2006-04-ShiningRunesAndShadowedHands/9 WeenieDefaults/Gem/32933 Son of Pooky's Den.sql
> +     , (32933,   3,         82) /* PaletteTemplate - PinkPurple */
Changed.

2020-09-04 17:56 UTC, ziang4891 approved these changes

2020-09-10 03:48 UTC, merged