Crystalline crag
ACEmulator/ACE-World-16PY-Patches pull request #626
Opened 2020-09-11 00:17 UTC by sLackeR-hub

Crystalline Crag and includes all quests/dungeons associated with it. (Excluding Exploration Markers)

2020-09-12 15:47 UTC, ziang4891 requested changes
The files within 9 WeenieDefaults shouldn't be just loose within this base folder but should be sorted into subfolders that follow the convention of WeenieType/ItemType

2020-09-12 15:50 UTC, ziang4891 requested changes

2020-09-12 15:50 UTC, ziang4891 commented on Database/Patches/2009-02-UnfinishedBusiness/9 WeenieDefaults/39984 Adventurer's Token.sql
> +
This weenie file already exists in a previous patch folder, and there are not differences between the two, so a duplicate is not needed in the 2009-02-UnfinishedBusiness patch directory tree

2020-09-12 15:53 UTC, ziang4891 commented
The creatures that don't have a PropertyInt.CreatureType should be placed in Creature\Unsorted subfolder tree

2020-09-12 16:21 UTC, ziang4891 requested changes

2020-09-12 16:21 UTC, ziang4891 commented on Database/Patches/2009-02-UnfinishedBusiness/9 WeenieDefaults/40100 Crystalline Shard.sql
> +     , (40100,  22,  872415275) /* PhysicsEffectTable */;
Use the file from ACE-PCAP-Dynamics-Exports, as it has the correct WeenieType and property composition

2020-09-12 16:21 UTC, ziang4891 commented on Database/Patches/2009-02-UnfinishedBusiness/9 WeenieDefaults/40103 Oorjit.sql
> +
The fixed Texture DIDs should be removed to allow for randomization

2020-09-12 16:21 UTC, ziang4891 commented on Database/Patches/2009-02-UnfinishedBusiness/9 WeenieDefaults/40099 Tokashi Ando.sql
> +
The fixed Texture DIDs should be removed to allow for randomization

2020-09-12 16:21 UTC, ziang4891 commented on Database/Patches/2009-02-UnfinishedBusiness/9 WeenieDefaults/40097 Jyotsana.sql
> +     , (40097,  17,   67109554) /* SkinPalette */;
The fixed Texture DIDs should be removed to allow for randomization

2020-09-12 16:23 UTC, ziang4891 commented
PropertyBools, like IgnoreCollisions, Ethereal, GravityStatus, and the like are not needed and can be removed with there is a matching PropertyInt.PhysicsState bitfield that contains the same properties

2020-09-14 13:11 UTC, sLackeR-hub commented on Database/Patches/2009-02-UnfinishedBusiness/9 WeenieDefaults/39984 Adventurer's Token.sql
> +
Removed/

2020-09-14 14:28 UTC, sLackeR-hub commented on Database/Patches/2009-02-UnfinishedBusiness/9 WeenieDefaults/40097 Jyotsana.sql
> +     , (40097,  17,   67109554) /* SkinPalette */;
Removed DIDs

2020-09-14 14:29 UTC, sLackeR-hub commented on Database/Patches/2009-02-UnfinishedBusiness/9 WeenieDefaults/40099 Tokashi Ando.sql
> +
Removed DIDs

2020-09-14 14:30 UTC, sLackeR-hub commented on Database/Patches/2009-02-UnfinishedBusiness/9 WeenieDefaults/40103 Oorjit.sql
> +
Removed DIDs.

2020-09-14 14:41 UTC, sLackeR-hub commented on Database/Patches/2009-02-UnfinishedBusiness/9 WeenieDefaults/40100 Crystalline Shard.sql
> +     , (40100,  22,  872415275) /* PhysicsEffectTable */;
Fixed.

2020-09-14 16:46 UTC, ziang4891 requested changes

2020-09-14 16:46 UTC, ziang4891 commented on Database/Patches/2009-02-UnfinishedBusiness/9 WeenieDefaults/Creature/Crystal/40106 Crystal.sql
> +
All of these ratings, especially when they are zero, should be removed from this weenie and others

2020-09-14 16:51 UTC, ziang4891 commented
If you move 40124 Crystal.sql to Generic/Misc and remove the PropertyInt ratings that are 0 from a couple of the Crystal NPCs, I think this PR should be good

2020-09-14 21:31 UTC, sLackeR-hub commented on Database/Patches/2009-02-UnfinishedBusiness/9 WeenieDefaults/Creature/Crystal/40106 Crystal.sql
> +
Fixed.

2020-09-14 22:39 UTC, ziang4891 requested changes
All of the Crystal NPCs that are not attackable should have the AiImmobile and NpcLooksLikeObject bools, as they are Creatures for the purposes of performing game mechanics but appraise as objects not creatures

2020-09-17 12:58 UTC, sLackeR-hub commented
> 
> 
> All of the Crystal NPCs that are not attackable should have the AiImmobile and NpcLooksLikeObject bools, as they are Creatures for the purposes of performing game mechanics but appraise as objects not creatures

2020-09-17 14:27 UTC, ziang4891 commented
Looks good.  I'll need to load it into my server to give it a test drive.

2020-09-19 15:52 UTC, ziang4891 requested changes
71868 Crystalline Array Fragment Generator.sql file shouldn't be in the **\B GameEventDefDB** folder but should be in **\9 WeenieDefaults\Generic\None**

2020-09-21 14:17 UTC, ziang4891 approved these changes

2020-09-26 02:32 UTC, ziang4891 requested changes

2020-09-26 02:32 UTC, ziang4891 commented on Database/Patches/2009-02-UnfinishedBusiness/9 WeenieDefaults/Creature/Wisp/42670 Shivering Crystalline Wisp.sql
> +
This file should not be here and shouldn't be used for the Crystalline Crag data.  This wcid of the wisp belongs to the Aetheria dungeons

2020-09-27 21:13 UTC, ziang4891 submitted a review, later dismissed

2020-09-27 22:21 UTC, sLackeR-hub commented on Database/Patches/2009-02-UnfinishedBusiness/9 WeenieDefaults/Creature/Wisp/42670 Shivering Crystalline Wisp.sql
> +
Removed.

2020-10-05 03:11 UTC, DridsGhost commented
316D looks like it has mangled data from 01970 High Direlands Mountain Generator.sql

You should pull out this data and clean up the landblock.

2020-10-05 03:12 UTC, DridsGhost commented
WeenieClassName: ace40104-resonantportal shows as a creature in the PCAP.

Why is this a white portal

2020-10-06 04:17 UTC, DridsGhost commented
All of your landblocks appear to use the generic dynamics linkables on 14 minute spawns. 01154.

Should they be that long?

2020-10-06 04:17 UTC, DridsGhost commented
`landblock` = 0x326A

More garbled with encounters gens

2020-10-06 04:21 UTC, DridsGhost commented on Database/Patches/2009-02-UnfinishedBusiness/9 WeenieDefaults/Creature/Unsorted/40104 Resonant Portal.sql
> +	  , (40104,  83, True ) /* NPCLooklike */;
This weenie should be a creature according to the PCAP

2020-10-06 14:35 UTC, sLackeR-hub commented on Database/Patches/2009-02-UnfinishedBusiness/9 WeenieDefaults/Creature/Unsorted/40104 Resonant Portal.sql
> +	  , (40104,  83, True ) /* NPCLooklike */;
Fixed

2020-10-06 23:58 UTC, DridsGhost commented on Database/Patches/2009-02-UnfinishedBusiness/6 LandBlockExtendedData/2D6B.sql
> +VALUES (0x72D6B06B, 0x72D6B06C, '2019-02-10 00:00:00') /* Acidic Diamond Golem (36829) */
This mob shouldnt be here

2020-10-07 01:18 UTC, DridsGhost commented
http://acpedia.org/wiki/Crystalline_Adventurer

Crystalline Shards
Kill various wisps throughout the Crystalline Crag and its dungeons.
Wisps will randomly drop a yellow-colored Crystalline Shard.
Hand them to Tokashi Ando for 50,000 xp each.
Note: There is no pickup timer and they are giveable. Any character of level 50+ can hand them in for the xp.
Note: You can only turn in 20 shards within a 20 hour period.

This quest excepts unlimited Crystalline Shards

--------------------------

2020-10-07 03:42 UTC, DridsGhost commented
Crystalline Bound Wisp

Currently it says
Bound Wisp tells you, "Excellent work in your hunt. We'll find your reports very useful."

It should be a DirectBroadcast: You have reached the bound wisp!

https://youtu.be/_XgTlViV6WE?t=218

2020-10-07 04:52 UTC, DridsGhost commented
Crystalline Essence Array should be default Scale of 2

2020-10-07 04:53 UTC, DridsGhost commented
Bound Wisp should cast 

Bound Wisp teleports you with Crystalline Portal.

Change dialouge to 
DirectBroadcast:
You have reached the bound wisp!

2020-10-07 05:13 UTC, DridsGhost commented
Landblock 326A

Needs to be cleaned up

2020-10-07 05:15 UTC, DridsGhost commented
Landblock 72E6 needs to be cleaned up

There are torches everywhere  not mentioned in the wiki. Likely a player drop.

Other various landscape creatures, supply crates, lugians etc..

2020-10-07 05:25 UTC, ziang4891 commented
Don't leave the static spawns of plants, either

2020-10-07 20:54 UTC, DridsGhost commented
Looks like we are missing contracts. Also CrystallineArrayFragmentPickupTimer.sql should be CrystalFinalPickup0509

And CrystallineMarkerQuest.sql should be CrystallineMarkerCounter0109

For the contracts to work.

Tokashi Ando			CrystalFinalPickup0509
Bound Wisp		       CrystallineSkillTest10109Wait
Oorjit				KillTaskCrystallineWisps10109		KillTaskCrystallineWisps10109Wait
Jyotsana				CrystallineMarkerCounter0109

2020-10-08 03:18 UTC, DridsGhost requested changes

2020-10-08 03:18 UTC, DridsGhost commented on Database/Patches/2009-02-UnfinishedBusiness/9 WeenieDefaults/Creature/Golem/40775 Ancient Golem.sql
> +VALUES (40775,   1,   33559702) /* Setup */
These guys have the wrong values. Should be

SETUP_DID (1): 0x02001496 (33559702)
CLOTHINGBASE_DID (7): 0x10000637 (268437047)
PALETTE_TEMPLATE_INT (3): 39 - Black
SHADE_FLOAT (12): 0

2020-10-08 03:18 UTC, DridsGhost commented on Database/Patches/2009-02-UnfinishedBusiness/9 WeenieDefaults/Creature/Golem/40775 Ancient Golem.sql
> +     , (40775,  35,       1026) /* DeathTreasureType - Loot Tier: 7 */;
These golems should be T6. Treasure type 

461) /* DeathTreasureType - Loot Tier: 6 */;

2020-10-08 12:56 UTC, sLackeR-hub commented on Database/Patches/2009-02-UnfinishedBusiness/6 LandBlockExtendedData/2D6B.sql
> +VALUES (0x72D6B0A2,  1542, 0x2D6B002F, 137.0873, 159.8326, 68.43377, 0.9980775, 0, 0, -0.06197855, False, '2019-02-10 00:00:00'); /* Linkable Item Generator */
Switched to 2 min gen

2020-10-08 13:00 UTC, sLackeR-hub commented on Database/Patches/2009-02-UnfinishedBusiness/6 LandBlockExtendedData/00C7.sql
> +VALUES (0x700C728B,  1542, 0x00C70390, 100, -70, 0, 1, 0, 0, 0, False, '2019-02-10 00:00:00'); /* Linkable Item Generator */
I guess I don't know either. These are the crystals that spawn the "rare" wisps so 13 should be fine? Let me know if anyone thinks I should change it.

2020-10-08 13:00 UTC, sLackeR-hub commented on Database/Patches/2009-02-UnfinishedBusiness/6 LandBlockExtendedData/326B.sql
> +     , (0x7326B001, 0x7326B00A, '2019-02-10 00:00:00') /* Pyreal Golem (36833) */
Removed.

2020-10-08 13:01 UTC, sLackeR-hub commented on Database/Patches/2009-02-UnfinishedBusiness/6 LandBlockExtendedData/326B.sql
> +     , (0x7326B001, 0x7326B026, '2019-02-10 00:00:00') /* Gotrok Tiatus (24497) */
Removed.

2020-10-08 13:13 UTC, sLackeR-hub commented on Database/Patches/2009-02-UnfinishedBusiness/9 WeenieDefaults/Generic/Misc/71867 Crystalline Array Fragment.sql
> +VALUES (71867,   1,   33557506) /* Setup */
Fixed, is white now.

2020-10-08 13:21 UTC, sLackeR-hub commented on Database/Patches/2009-02-UnfinishedBusiness/9 WeenieDefaults/Creature/Golem/40775 Ancient Golem.sql
> +VALUES (40775,   1,   33559702) /* Setup */
Fixed

2020-10-08 13:23 UTC, sLackeR-hub commented on Database/Patches/2009-02-UnfinishedBusiness/9 WeenieDefaults/Creature/Golem/40775 Ancient Golem.sql
> +     , (40775,  35,       1026) /* DeathTreasureType - Loot Tier: 7 */;
Fixed.

2020-10-08 19:22 UTC, DridsGhost commented on Database/Patches/2009-02-UnfinishedBusiness/6 LandBlockExtendedData/00C7.sql
> +VALUES (0x700C728B,  1542, 0x00C70390, 100, -70, 0, 1, 0, 0, 0, False, '2019-02-10 00:00:00'); /* Linkable Item Generator */
Fine by me. We can wait for it to go live and adjust if necessary.

2020-10-23 03:45 UTC, ziang4891 commented on Database/Patches/2009-02-UnfinishedBusiness/9 WeenieDefaults/Generic/Misc/71867 Crystalline Array Fragment.sql
> +VALUES (71867, 'ace71867-CrystallineArrayFragment', 38, '2020-08-21 23:49:56') /* Gem */;
Why did you change this item to a Gem from Generic?  Generic fits better, given the background of the icon.

2020-10-23 14:28 UTC, sLackeR-hub reviewed
Not sure why this is a review sorry.

2020-10-23 14:28 UTC, sLackeR-hub commented on Database/Patches/2009-02-UnfinishedBusiness/9 WeenieDefaults/Generic/Misc/71867 Crystalline Array Fragment.sql
> +VALUES (71867, 'ace71867-CrystallineArrayFragment', 38, '2020-08-21 23:49:56') /* Gem */;
That is a good question I don't recall changing it, but I do see the value remained the same for type so I am guessing the /export updated the comment.

2020-10-24 20:46 UTC, ziang4891 commented on Database/Patches/2009-02-UnfinishedBusiness/9 WeenieDefaults/Generic/Misc/71867 Crystalline Array Fragment.sql
> +VALUES (71867, 'ace71867-CrystallineArrayFragment', 38, '2020-08-21 23:49:56') /* Gem */;
The weenietype value changed from 1 to 38, which is why the comment changed.  It needs to be changed back to a Generic item.  It is not a Gem

2020-10-25 01:33 UTC, sLackeR-hub commented on Database/Patches/2009-02-UnfinishedBusiness/9 WeenieDefaults/Generic/Misc/71867 Crystalline Array Fragment.sql
> +VALUES (71867, 'ace71867-CrystallineArrayFragment', 38, '2020-08-21 23:49:56') /* Gem */;
Fixed/reverted.

2020-10-25 21:19 UTC, ziang4891 submitted a review, later dismissed

2020-11-27 17:33 UTC, ziang4891 approved these changes

2021-01-01 23:05 UTC, ziang4891 commented
Will require cumulative inclusion of PRs 3405, 3406, and 3407 from ACE

2021-01-01 23:06 UTC, ziang4891 approved these changes

2021-01-03 08:36 UTC, merged