Crystal Core Quest
ACEmulator/ACE-World-16PY-Patches pull request #628
Opened 2020-09-14 21:57 UTC by sLackeR-hub

Crystal Core Quest plus update to Frost Haven including fixing Robert/Adding David.  Also added Crystal Core portal to Landblock 9F2C.

2020-09-14 22:29 UTC, ziang4891 requested changes

2020-09-14 22:29 UTC, ziang4891 commented on Database/Patches/2012-12-AGrowingTwilight/9 WeenieDefaults/Creature/Crystal/48717 Crystal.sql
> +     , (48717,  19, False) /* Attackable */;
Missing AiImmobile and NpcLooksLikeObject

2020-09-14 22:29 UTC, ziang4891 commented on Database/Patches/2012-12-AGrowingTwilight/9 WeenieDefaults/Creature/Crystal/48723 Crystal.sql
> +     , (48723,  19, False) /* Attackable */;
Missing AiImmobile and NpcLooksLikeObject

2020-09-14 22:29 UTC, ziang4891 commented on Database/Patches/2012-12-AGrowingTwilight/9 WeenieDefaults/Creature/Elemental/48711 Scorching Flame.sql
> +     , (48711,   6,         -1) /* ItemsCapacity */
Missing CreatureType property; should be CreatureType - Elemental

2020-09-14 22:29 UTC, ziang4891 commented on Database/Patches/2012-12-AGrowingTwilight/9 WeenieDefaults/Creature/Golem/48712 Char Golem.sql
> +     , (48712,   6,         -1) /* ItemsCapacity */
Missing CreatureType property; should be CreatureType - Golem

2020-09-14 22:29 UTC, ziang4891 commented on Database/Patches/2012-12-AGrowingTwilight/9 WeenieDefaults/Creature/Wall/48718 Wall of Ice.sql
> +     , (48718,  19, False) /* Attackable */;
Missing AiImmobile and NpcLooksLikeObject

2020-09-14 22:29 UTC, ziang4891 commented on Database/Patches/2012-12-AGrowingTwilight/9 WeenieDefaults/Creature/Wall/48724 Wall of Ice.sql
> +     , (48724,  19, False) /* Attackable */;
Missing AiImmobile and NpcLooksLikeObject

2020-09-14 22:29 UTC, ziang4891 commented on Database/Patches/2012-12-AGrowingTwilight/9 WeenieDefaults/PressurePlate/71870 Pressure Plate.sql
> +VALUES (@parent_id, 0, 88 /* LocalSignal */, 0, 1, NULL, 'Scold', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, N
Probably shouldn't have the LocalSignal send be the first action before the chat text, as the golem may disappear before the text is sent, which would look odd

2020-09-14 22:29 UTC, ziang4891 commented on Database/Patches/2012-12-AGrowingTwilight/9 WeenieDefaults/Creature/Crystal/48713 Blazing Crystal.sql
> +     , (48713,   6,         -1) /* ItemsCapacity */
Missing CreatureType property; should be CreatureType - Crystal

2020-09-14 22:29 UTC, ziang4891 commented on Database/Patches/2012-12-AGrowingTwilight/9 WeenieDefaults/Creature/Crystal/48715 Prism Shard.sql
> +     , (48715,   6,         -1) /* ItemsCapacity */
Missing CreatureType property; should be CreatureType - Crystal

2020-09-14 22:29 UTC, ziang4891 commented on Database/Patches/2012-12-AGrowingTwilight/9 WeenieDefaults/Creature/Crystal/48720 Crystal.sql
> +VALUES (48720,   1,        128) /* ItemType - Misc */
Not a creature so should be in Generic/Misc subfolders

2020-09-15 13:06 UTC, sLackeR-hub commented on Database/Patches/2012-12-AGrowingTwilight/9 WeenieDefaults/Creature/Crystal/48717 Crystal.sql
> +     , (48717,  19, False) /* Attackable */;
Added.

2020-09-15 13:06 UTC, sLackeR-hub commented on Database/Patches/2012-12-AGrowingTwilight/9 WeenieDefaults/Creature/Crystal/48723 Crystal.sql
> +     , (48723,  19, False) /* Attackable */;
Added.

2020-09-15 13:08 UTC, sLackeR-hub commented on Database/Patches/2012-12-AGrowingTwilight/9 WeenieDefaults/Creature/Wall/48718 Wall of Ice.sql
> +     , (48718,  19, False) /* Attackable */;
Added

2020-09-15 13:08 UTC, sLackeR-hub commented on Database/Patches/2012-12-AGrowingTwilight/9 WeenieDefaults/Creature/Wall/48724 Wall of Ice.sql
> +     , (48724,  19, False) /* Attackable */;
Added

2020-09-15 13:09 UTC, sLackeR-hub commented on Database/Patches/2012-12-AGrowingTwilight/9 WeenieDefaults/PressurePlate/71870 Pressure Plate.sql
> +VALUES (@parent_id, 0, 88 /* LocalSignal */, 0, 1, NULL, 'Scold', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, N
With the delays in both it works out perfect.

2020-09-15 13:16 UTC, sLackeR-hub commented on Database/Patches/2012-12-AGrowingTwilight/9 WeenieDefaults/Creature/Elemental/48711 Scorching Flame.sql
> +     , (48711,   6,         -1) /* ItemsCapacity */
Added Fire Elemental type

2020-09-15 13:18 UTC, sLackeR-hub commented on Database/Patches/2012-12-AGrowingTwilight/9 WeenieDefaults/Creature/Golem/48712 Char Golem.sql
> +     , (48712,   6,         -1) /* ItemsCapacity */
Added Golem Type

2020-09-15 13:19 UTC, sLackeR-hub commented on Database/Patches/2012-12-AGrowingTwilight/9 WeenieDefaults/Creature/Crystal/48713 Blazing Crystal.sql
> +     , (48713,   6,         -1) /* ItemsCapacity */
Added Crystal Type

2020-09-15 13:20 UTC, sLackeR-hub commented on Database/Patches/2012-12-AGrowingTwilight/9 WeenieDefaults/Creature/Crystal/48715 Prism Shard.sql
> +     , (48715,   6,         -1) /* ItemsCapacity */
Added Crystal Type

2020-09-15 13:20 UTC, sLackeR-hub commented on Database/Patches/2012-12-AGrowingTwilight/9 WeenieDefaults/Creature/Crystal/48720 Crystal.sql
> +VALUES (48720,   1,        128) /* ItemType - Misc */
Moved.

2020-09-16 14:08 UTC, ziang4891 requested changes

2020-09-16 14:08 UTC, ziang4891 commented on Database/Patches/2012-12-AGrowingTwilight/9 WeenieDefaults/Creature/Wall/48718 Wall of Ice.sql
> +     , (48718,  83, True) /* Attackable */;
Comment for the above two properties isn't correct

2020-09-16 14:08 UTC, ziang4891 commented on Database/Patches/2012-12-AGrowingTwilight/9 WeenieDefaults/Creature/Wall/48724 Wall of Ice.sql
> +     , (48724,  83, True) /* Attackable */;
Comment for the above two properties isn't correct

2020-09-17 12:43 UTC, sLackeR-hub commented on Database/Patches/2012-12-AGrowingTwilight/9 WeenieDefaults/Creature/Wall/48718 Wall of Ice.sql
> +     , (48718,  83, True) /* Attackable */;
Fixed.

2020-09-17 12:44 UTC, sLackeR-hub commented on Database/Patches/2012-12-AGrowingTwilight/9 WeenieDefaults/Creature/Wall/48724 Wall of Ice.sql
> +     , (48724,  83, True) /* Attackable */;
Fixed

2020-09-19 17:15 UTC, ziang4891 requested changes

2020-09-19 17:15 UTC, ziang4891 commented on Database/Patches/2012-12-AGrowingTwilight/9 WeenieDefaults/Creature/Golem/48712 Char Golem.sql
> +     , (48712, 9,  2434,  0, 0, 0, False) /* Create Lesser Mana Stone (2434) for ContainTreasure */;
CreateList entries like this should be removed, as these entries are just representative of what the mob dropped when PCAP'ed.  To add random loot to mobs, it needs to be added via DeathTreasureDID that goes in the weenie_properties_d_i_d table.  An entry of **(48712,  35,        462) /* DeathTreasureType - Loot Tier: 3 */** would probably be appropriate

2020-09-19 17:15 UTC, ziang4891 commented on Database/Patches/2012-12-AGrowingTwilight/9 WeenieDefaults/Creature/Golem/48712 Char Golem.sql
> +     , (48712, 9,  2434,  0, 0, 0, False) /* Create Lesser Mana Stone (2434) for ContainTreasure */;
Also, golems like this one should have two heartbeat emotes for wiring up their sleep and wait animations, like https://github.com/ACEmulator/ACE-World-16PY-Patches/blob/173fd0605f8163efa5edf0d7d4dc1afeb65a5d71/Database/Patches/2005-07-ThroneOfDestiny/9%20WeenieDefaults/Creature/Golem/00200%20Mud%20Golem.sql#L135

2020-09-19 17:22 UTC, ziang4891 requested changes
init_Level values in weenie_properties_attribute_2nd table need to be fixed as described in content_recreation Discord channel

2020-09-20 14:33 UTC, sLackeR-hub commented on Database/Patches/2012-12-AGrowingTwilight/9 WeenieDefaults/Creature/Elemental/48711 Scorching Flame.sql
> +
Fixed.

2020-09-20 14:58 UTC, sLackeR-hub commented on Database/Patches/2012-12-AGrowingTwilight/9 WeenieDefaults/Creature/Golem/48712 Char Golem.sql
> +     , (48712, 9,  2434,  0, 0, 0, False) /* Create Lesser Mana Stone (2434) for ContainTreasure */;
Fixed.

2020-09-20 15:06 UTC, sLackeR-hub commented on Database/Patches/2012-12-AGrowingTwilight/9 WeenieDefaults/Creature/Elemental/48711 Scorching Flame.sql
> +
Fixed.

2020-09-21 14:16 UTC, ziang4891 submitted a review, later dismissed

2020-10-04 06:51 UTC, DridsGhost approved these changes

2020-10-07 21:13 UTC, DridsGhost requested changes
Missing contracts, probably need to rename the quest entries.

David
BuriedAliveStarted1212
BuriedAliveCompleted1212

2020-10-07 21:13 UTC, DridsGhost commented on Database/Patches/2012-12-AGrowingTwilight/8 QuestDefDB/blazingshardpickup.sql
> +DELETE FROM quest WHERE name = 'blazingshardpickup';
Missing contracts, probably need to rename the quest entries.

David 
BuriedAliveStarted1212 
BuriedAliveCompleted1212

2020-10-07 21:13 UTC, DridsGhost commented on Database/Patches/2012-12-AGrowingTwilight/8 QuestDefDB/crystalcorestart.sql
> +DELETE FROM quest WHERE name = 'crystalcorestart';
Missing contracts, probably need to rename the quest entries.

David
BuriedAliveStarted1212
BuriedAliveCompleted1212

2020-10-07 22:39 UTC, DridsGhost approved these changes
nice job

2020-10-09 13:54 UTC, ziang4891 approved these changes

2020-10-10 18:40 UTC, merged