Rescuing Mouf P
ACEmulator/ACE-World-16PY-Patches pull request #638
Opened 2020-09-17 21:43 UTC by sLackeR-hub

*Completed Quest*

Update to Larinne Kerendova to accept Letters / Give EXP for Igloo

**Added:**
Mr. P
Hoarfrost
Letter from Uber P
Uber P
Mouf
Letter from Mouf
Letter from Mouf and Uber P
Baby Penguin
Penguin Guardian 
Cowardly Snowman
Tiny's Head
Door
Lever
Tiny
Pillar of Frost
Wall of Ice
Frigid Grotto
Frigid Ice Golem
Frigid Mist Golem
Penguin Guard
Surface
Security Station
Security Door

**Added to Landblocks:**
Uber P
Mr. P
Frigid Grotto Portal

2020-09-19 17:40 UTC, ziang4891 requested changes
init_Level values in weenie_properties_attribute_2nd table need to be fixed as described in content_recreation Discord channel

2020-09-19 18:29 UTC, ziang4891 requested changes
Weenies with ClothingBase should probably have an associated PaletteTemplate INT property, which can usually be found by searching for the wcid on Optim's site (http://ac.yotesfan.com/)

2020-09-19 18:29 UTC, ziang4891 commented on Database/Patches/2012-07-SoullessSisters/9 WeenieDefaults/Creature/Human/33939 Larinne Kerendova.sql
> +
If you bring a weenie file forward in patches, the original should be removed; this NPC also exists in 2006-09-ComeWhatFollows patch folder

2020-09-19 18:29 UTC, ziang4891 commented on Database/Patches/2012-07-SoullessSisters/9 WeenieDefaults/Creature/Penguin/46299 Tiny.sql
> +     , (46299, 9,   133,  0, 0, 0, False) /* Create Slippers (133) for ContainTreasure */;
This table should be condensed down to just the Tiny's Head entry, as the other items were just a snapshot of the random loot at the time of capture, which DeathTreasureType should cover.  Also, for Tiny's Head, shade would be set to 1, as that data point is actually treated as probability of dropping for ContainTreasure.  A zero would mean it doesn't drop at all.

2020-09-19 18:29 UTC, ziang4891 commented on Database/Patches/2012-07-SoullessSisters/9 WeenieDefaults/Creature/Snowman/46278 Cowardly Snowman.sql
> +
A level 105 mob is not likely to have tier 7 loot

2020-09-19 18:29 UTC, ziang4891 commented on Database/Patches/2012-07-SoullessSisters/9 WeenieDefaults/Creature/Snowman/46278 Cowardly Snowman.sql
> +
ThrownWeapon skill is covered by MissileWeapons, so doesn't need to be added

2020-09-19 18:29 UTC, ziang4891 commented on Database/Patches/2012-07-SoullessSisters/9 WeenieDefaults/Creature/Unsorted/46303 Wall of Ice.sql
> +
Missing NpcLooksLikeObject and a CombatTable entry in weenie_properties_d_i_d.  Can probably use the one from https://github.com/ACEmulator/ACE-World-16PY-Patches/blob/master/Database/Patches/2005-12-ThroughSacrificeStrength/9%20WeenieDefaults/Creature/Unsorted/80027%20Mana%20Barrier.sql

2020-09-19 18:29 UTC, ziang4891 commented on Database/Patches/2012-07-SoullessSisters/9 WeenieDefaults/Creature/Unsorted/46320 Security Station.sql
> +     , (46320,  19, False) /* Attackable */;
Missing NpcLooksLikeObject property

2020-09-19 18:29 UTC, ziang4891 commented on Database/Patches/2012-07-SoullessSisters/9 WeenieDefaults/Portal/46308 Surface.sql
> +     , (46308,   8,  100667499) /* Icon */;
Missing weenie_properties_position Destination

2020-09-20 04:37 UTC, sLackeR-hub commented on Database/Patches/2012-07-SoullessSisters/9 WeenieDefaults/Creature/Elemental/42338 Hoarfrost.sql
> +VALUES (42338, 9,  6876,  0, 0, 0.001, False) /* Create Sturdy Iron Key (6876) for ContainTreasure */;
Fixed Hoarfrost completely. Going through all other critters.

2020-09-20 04:45 UTC, sLackeR-hub commented on Database/Patches/2012-07-SoullessSisters/9 WeenieDefaults/Creature/Elemental/46300 Pillar of Frost.sql
> +     , (46300,  3878,      3) /* Incendiary Strike */;
Fixed

2020-09-20 04:46 UTC, sLackeR-hub commented on Database/Patches/2012-07-SoullessSisters/9 WeenieDefaults/Creature/Elemental/46300 Pillar of Frost.sql
> +/* @teleloc 0x584D010A [100.004500 -59.593110 -24.003340] 0.797037 0.000000 0.000000 -0.603931 */;
Removed

2020-09-20 04:46 UTC, sLackeR-hub commented on Database/Patches/2012-07-SoullessSisters/9 WeenieDefaults/Creature/Elemental/46300 Pillar of Frost.sql
> +     , (46300,  8,  4,1000, 0.75,  500,  250,  250,  250,  250,  250,  250,  250,    0, 3,    0,    0, 0.22,    0,    0, 0.22,    0,    0, 0.22,    0,    0, 0.22) /* Foot - Bludgeon */;
Changed to 10.

2020-09-20 15:56 UTC, sLackeR-hub commented on Database/Patches/2012-07-SoullessSisters/9 WeenieDefaults/Creature/Unsorted/46303 Wall of Ice.sql
> +
Fixed.

2020-09-20 15:56 UTC, sLackeR-hub commented on Database/Patches/2012-07-SoullessSisters/9 WeenieDefaults/Creature/Golem/46305 Frigid Ice Golem.sql
> +
Fixed.

2020-09-20 15:56 UTC, sLackeR-hub commented on Database/Patches/2012-07-SoullessSisters/9 WeenieDefaults/Creature/Snowman/46278 Cowardly Snowman.sql
> +
Changed to 6

2020-09-20 15:57 UTC, sLackeR-hub commented on Database/Patches/2012-07-SoullessSisters/9 WeenieDefaults/Creature/Snowman/46278 Cowardly Snowman.sql
> +
Removed/

2020-09-20 15:57 UTC, sLackeR-hub commented on Database/Patches/2012-07-SoullessSisters/9 WeenieDefaults/Creature/Unsorted/46320 Security Station.sql
> +     , (46320,  19, False) /* Attackable */;
Added

2020-09-20 16:05 UTC, sLackeR-hub commented on Database/Patches/2012-07-SoullessSisters/9 WeenieDefaults/Portal/46308 Surface.sql
> +     , (46308,   8,  100667499) /* Icon */;
Fixed.

2020-09-21 16:12 UTC, ziang4891 approved these changes

2020-10-04 06:09 UTC, DridsGhost approved these changes

2020-10-10 18:57 UTC, merged