Add Amelia's Lost Toys quest
ACEmulator/ACE-World-16PY-Patches pull request #650
Opened 2020-09-23 15:18 UTC by sbaum23

The basic flow of the quest is that the player talks to Amelia (35932) which
pops up a yes/no box. If the player accepts then a signal is sent to spawn
Amelia (35933), then Amelia (35932) despawns. Amelia will then run to
certain points and emit a signal.

There are generators setup at each location which listen for
the signal and then spawn a specific dirt pile. The dirt pile last for 30
seconds and then disappear. When the player interacts with the dirt pile
it will give them a specific toy.

After going to the last dirt pile Amelia (35933) will run home, emit a
signal to spawn the original version (35932), then despawn.

Amelia (35932) will accept the toys and give a reward once all 6 toys have
been handed over.

Information on dirt pile locations was taken from PCAP but also from this
video: https://www.youtube.com/watch?v=9SyAqFNuwzo. Not all locations were
shown in the video so some guesswork was done.

2020-10-03 16:43 UTC, ziang4891 requested changes

2020-10-03 16:43 UTC, ziang4891 commented on Database/Patches/2007-08-CorruptedSovereigns/6 LandBlockExtendedData/482E.sql
> +/* @teleloc 0x482e0023 110.113 59.89 9.031 0.897 0 0 0.442 */
Would need an event type generator to respawn the "static" version of Amelia that would be enabled, when the overarching event ends.  With her being spawned by the landblock instance table, should would only show back up on server restart.

2020-10-03 16:43 UTC, ziang4891 commented on Database/Patches/2007-08-CorruptedSovereigns/9 WeenieDefaults/Creature/Ghost/35932 Amelia.sql
> +
Rather than performing a DeleteSelf, she would be tied to an event generator and call event end to remove the "static" spawn.  See comment on landblock file.

2020-10-03 16:43 UTC, ziang4891 commented on Database/Patches/2007-08-CorruptedSovereigns/9 WeenieDefaults/Creature/Ghost/35933 Amelia.sql
> +
Generator that spawns the moving version of Amelia should be an event based generator, which would get disabled when the overarching event ends, rather than using DeleteSelf.  Also, on event end, start the event controlling the static Amelia spawn.

2020-10-03 16:47 UTC, ziang4891 commented
Using LocalSignals is all well and good, but on return trip of moving Amelia, there isn't anything to hear the signal to respawn the static Amelia, as she deleted herself with the event started.

2020-10-03 17:58 UTC, sbaum23 commented
> 
> 
> Using LocalSignals is all well and good, but on return trip of moving Amelia, there isn't anything to hear the signal to respawn the static Amelia, as she deleted herself with the event started.

@ziang4891 [80077 Amelia Generator.sql](https://github.com/ACEmulator/ACE-World-16PY-Patches/pull/650/files#diff-37cb6ad8045a762b32030c814298f5c8) is the generator that spawns the static version when the quest is over.

2020-10-03 18:02 UTC, sbaum23 commented on Database/Patches/2007-08-CorruptedSovereigns/9 WeenieDefaults/Creature/Ghost/35933 Amelia.sql
> +
There are two generators that spawn the different versions of Amelia based on local signals: 

- [80076 Amelia Wanderer Generator.sql](https://github.com/ACEmulator/ACE-World-16PY-Patches/pull/650/files#diff-86de8a82252a9ea0dff6dad0a25d9ef7) spawns the version that runs around to the different points.
- [80077 Amelia Generator.sql](https://github.com/ACEmulator/ACE-World-16PY-Patches/pull/650/files#diff-37cb6ad8045a762b32030c814298f5c8) spawns the static version after the wanderer sends a local signal when "returning home".

2020-10-03 19:04 UTC, ziang4891 commented
Why are you spawning her talking mode twice, then?  35932 is listed directly in the landblock file, also.  It needs to be configured only one way, which looks like through generator 80077.  Setup the event to be able to autostart inself, without having to add wcid 35932 to the landblock directly, also.

2020-10-03 20:12 UTC, sbaum23 commented
> 
> 
> Why are you spawning her talking mode twice, then? 35932 is listed directly in the landblock file, also. It needs to be configured only one way, which looks like through generator 80077. Setup the event to be able to autostart itself, without having to add wcid 35932 to the landblock directly, also.

@ziang4891 Are you concerned that two versions of 35932 will be spawned? With the way it is currently setup I don't think it is possible. 35932 is initially created from the landblock file. When someone starts the quest, it deletes itself and won't respawn until the wanderer (35933) sends out the local signal.

Are you saying to have the generator auto generate when it is spawned? How do I do that? Is it the `when_create` field in the generator table?

2020-10-04 22:01 UTC, ziang4891 commented
Add another event for AmeliaTalking phase, and have it enabled by default, and modify the generator that spawns 35932 to use this new event.  When wcid 35932 is done with its speech, have it StopEvent for AmeliaTalking, instead of using DeleteSelf, along with toggling the moving Amelia phase event.  When the moving phase is finished, wcid 35933 will StopEvent on the moving Amelia phase event, and then enable the AmeliaTalking phase, again, instead of DeleteSelf.

2020-10-28 05:57 UTC, merged