Graveyard + Kill Tasks and DeathTail
ACEmulator/ACE-World-16PY-Patches pull request #653
Opened 2020-10-02 22:37 UTC by sLackeR-hub

**Graveyard and Kill Tasks**

**Added**
Too much to List

2020-10-03 16:13 UTC, ziang4891 approved these changes

2020-10-03 16:13 UTC, ziang4891 commented on Database/Patches/2007-03-AncientEnemies/9 WeenieDefaults/Creatures/Undead/35091 Wight.sql
> +     , (35091, 307,       5) /* DamageRating */;
This rating comes from a wielded weapon

2020-10-03 16:13 UTC, ziang4891 commented on Database/Patches/2007-03-AncientEnemies/9 WeenieDefaults/Creatures/Undead/35091 Wight.sql
> +     , (35091,  43, 0, 2, 0, 310, 0, 0) /* VoidMagic */
Doesn't need VoidMagic skill

2020-10-03 16:13 UTC, ziang4891 commented on Database/Patches/2007-03-AncientEnemies/9 WeenieDefaults/Creatures/Undead/35092 Wight Captain.sql
> +     , (35092,  43, 0, 2, 0, 310, 0, 0) /* VoidMagic */
Doesn't need VoidMagic

2020-10-03 16:13 UTC, ziang4891 commented on Database/Patches/2007-03-AncientEnemies/9 WeenieDefaults/Creatures/Undead/35093 Wight Blade Sorcerer.sql
> +     , (35093,  43, 0, 2, 0, 340, 0, 0) /* VoidMagic */
Doesn't need VoidMagic

2020-10-03 16:13 UTC, ziang4891 commented on Database/Patches/2007-03-AncientEnemies/9 WeenieDefaults/Creatures/Undead/35093 Wight Blade Sorcerer.sql
> +VALUES (35093, 2, 31822,  1, 0, 0, False) /* Create Electric Baton (31822) for Wield */
If the intention is the build a caster only mob, the wielded baton is going to cause CombatManeuver errors because of melee combat and wielded casters are incompatible.  Spells would need to be set to 2.5+, including one set to 3, to preclude melee combat

2020-10-03 16:13 UTC, ziang4891 commented on Database/Patches/2007-03-AncientEnemies/9 WeenieDefaults/Creatures/Undead/41966 Wight.sql
> +     , (41966,  43, 0, 2, 0, 310, 0, 0) /* VoidMagic */
Doesn't need VoidMagic

2020-10-03 16:13 UTC, ziang4891 commented on Database/Patches/2007-03-AncientEnemies/9 WeenieDefaults/Creatures/Undead/41968 Wight Captain.sql
> +INSERT INTO `weenie_properties_create_list` (`object_Id`, `destination_Type`, `weenie_Class_Id`, `stack_Size`, `palette`, `shade`, `try_To_Bond`)
Missing a skill table

2020-10-03 16:13 UTC, ziang4891 commented on Database/Patches/2007-03-AncientEnemies/9 WeenieDefaults/Creatures/Undead/46815 Wight Blade Sorcerer.sql
> +     , (46815,  43, 0, 2, 0, 340, 0, 0) /* VoidMagic */
Doesn't need VoidMagic

2020-10-03 16:13 UTC, ziang4891 commented on Database/Patches/2013-12-FowlPlay/9 WeenieDefaults/Creature/Unsorted/52305 Corrupted Gravestone.sql
> +     , (52305, 0.54, 87005, 300, 1, 1, 1, 2, -1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0) /* Generate GY Day Wight Three Camp Gen (87005) (x1 up to max of 1) - Regenerate upon Destruction - Location to (re)Gene
Should set the generated mobs directly in this generator table, and appropriate probabilities, rather intermediary generators

2020-10-03 16:15 UTC, ziang4891 requested changes

2020-10-03 16:15 UTC, ziang4891 commented on Database/Patches/2007-03-AncientEnemies/9 WeenieDefaults/Creatures/Undead/35093 Wight Blade Sorcerer.sql
> +VALUES (35093, 2, 31822,  1, 0, 0, False) /* Create Electric Baton (31822) for Wield */
If not a caster only mob, this wielded baton should be removed, especially since it doesn't match the other Wight Blade Sorcerer wcids

2020-10-03 18:56 UTC, sLackeR-hub commented on Database/Patches/2007-03-AncientEnemies/9 WeenieDefaults/Creatures/Rat/35100 Grave Rat.sql
> +     , (35100,  34, 0, 2, 0, 149, 0, 0) /* WarMagic */;
Fixed.

2020-10-03 18:57 UTC, sLackeR-hub commented on Database/Patches/2007-03-AncientEnemies/9 WeenieDefaults/Creatures/Undead/35091 Wight.sql
> +     , (35091, 307,       5) /* DamageRating */;
Fixed.

2020-10-03 18:57 UTC, sLackeR-hub commented on Database/Patches/2007-03-AncientEnemies/9 WeenieDefaults/Creatures/Undead/35091 Wight.sql
> +     , (35091,  43, 0, 2, 0, 310, 0, 0) /* VoidMagic */
Fixed.

2020-10-03 18:59 UTC, sLackeR-hub commented on Database/Patches/2007-03-AncientEnemies/9 WeenieDefaults/Creatures/Undead/41966 Wight.sql
> +     , (41966,  43, 0, 2, 0, 310, 0, 0) /* VoidMagic */
Fixed.

2020-10-03 19:00 UTC, sLackeR-hub commented on Database/Patches/2007-03-AncientEnemies/9 WeenieDefaults/Creatures/Undead/41968 Wight Captain.sql
> +INSERT INTO `weenie_properties_create_list` (`object_Id`, `destination_Type`, `weenie_Class_Id`, `stack_Size`, `palette`, `shade`, `try_To_Bond`)
Fixed.

2020-10-03 19:01 UTC, sLackeR-hub commented on Database/Patches/2007-03-AncientEnemies/9 WeenieDefaults/Creatures/Undead/46815 Wight Blade Sorcerer.sql
> +     , (46815,  43, 0, 2, 0, 340, 0, 0) /* VoidMagic */
Fixed.

2020-10-03 19:18 UTC, sLackeR-hub commented on Database/Patches/2007-03-AncientEnemies/6 LandBlockExtendedData/482E.sql
> +/* @teleloc 0x482E0031 [146.729000 21.156800 67.998750] 0.920523 0.000000 0.000000 0.390689 */
Fixed and tested.

2020-10-07 00:47 UTC, ziang4891 requested changes

2020-10-07 00:47 UTC, ziang4891 commented on Database/Patches/2013-12-FowlPlay/9 WeenieDefaults/Creature/Unsorted/52305 Corrupted Gravestone.sql
> +     , (52305, 0.54, 87005, 300, 1, 1, 1, 2, -1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0) /* Generate GY Day Wight Three Camp Gen (87005) (x1 up to max of 1) - Regenerate upon Destruction - Location to (re)Gene
Set GeneratorRadius to cause the mobs to not stack on this generator, when spawned directly.  There isn't any need to stack generators for this one.

2020-10-07 00:47 UTC, ziang4891 commented on Database/Patches/2013-12-FowlPlay/9 WeenieDefaults/Creature/Unsorted/52305 Corrupted Gravestone.sql
> +     , (52305, 315,       9999) /* CritResistRating */;
Should have at least CombatMode - NonCombat , if not Tolerance - NoAttack, to ensure the mob doesn't try to perform combat itself, when it cannot

2020-10-08 19:34 UTC, sLackeR-hub commented on Database/Patches/2013-12-FowlPlay/9 WeenieDefaults/Creature/Unsorted/52305 Corrupted Gravestone.sql
> +     , (52305, 315,       9999) /* CritResistRating */;
Fixed. Tolerance No Attack seemed to cause issues with Scream. NonCombat worked.

2020-10-20 03:48 UTC, DridsGhost commented on Database/Patches/2007-03-AncientEnemies/9 WeenieDefaults/Creatures/Undead/46815 Wight Blade Sorcerer.sql
> +     , (46815,   6, 480, 0, 0) /* Self */;
Stats are Wrong. Please re-evaluate these mobs and mimic the frozen valley wights already in the world database for skills and body parts

INSERT INTO `weenie_properties_attribute` (`object_Id`, `type`, `init_Level`, `level_From_C_P`, `c_P_Spent`)
VALUES (46815,   1, 240, 0, 0) /* Strength */
     , (46815,   2, 220, 0, 0) /* Endurance */
     , (46815,   3, 210, 0, 0) /* Quickness */
     , (46815,   4, 230, 0, 0) /* Coordination */
     , (46815,   5, 325, 0, 0) /* Focus */
     , (46815,   6, 305, 0, 0) /* Self */;

INSERT INTO `weenie_properties_attribute_2nd` (`object_Id`, `type`, `init_Level`, `level_From_C_P`, `c_P_Spent`, `current_Level`)
VALUES (46815,   1,  3390, 0, 0, 3500) /* MaxHealth */
     , (46815,   3,  3000, 0, 0, 3220) /* MaxStamina */
     , (46815,   5,  2000, 0, 0, 2305) /* MaxMana */;

2020-10-20 03:54 UTC, DridsGhost commented on Database/Patches/2008-08-AncientPowers/9 WeenieDefaults/Creature/Undead/38713 Shambling Archivist.sql
> +INSERT INTO `weenie_properties_skill` (`object_Id`, `type`, `level_From_P_P`, `s_a_c`, `p_p`, `init_Level`, `resistance_At_Last_Check`, `last_Used_Time`)
The PCAP lists this mob with like 4110 health. I think the wiki is outdated.

Probably wanna beef this guy up also.

2020-10-22 21:14 UTC, sLackeR-hub commented on Database/Patches/2007-03-AncientEnemies/9 WeenieDefaults/Creatures/Undead/46815 Wight Blade Sorcerer.sql
> +     , (46815,   6, 480, 0, 0) /* Self */;
Fixed.

2020-10-22 21:15 UTC, sLackeR-hub commented on Database/Patches/2008-08-AncientPowers/9 WeenieDefaults/Creature/Undead/38713 Shambling Archivist.sql
> +INSERT INTO `weenie_properties_skill` (`object_Id`, `type`, `level_From_P_P`, `s_a_c`, `p_p`, `init_Level`, `resistance_At_Last_Check`, `last_Used_Time`)
Fixed. *Still needs society quest tag*

2020-10-24 17:28 UTC, ziang4891 requested changes

2020-10-24 17:28 UTC, ziang4891 commented on Database/Patches/2013-11-FowlPlay/9 WeenieDefaults/Creature/Unsorted/52305 Corrupted Gravestone.sql
> +
Please remove IgnoreCollisions, ReportCollisions, Ethereal, GravityStatus, and Attackable, as they are already handled by PropertyInt.PhysicsState; add NeverAttack bool to prevent GetCombatManeuver() error messages in the server log.  This faux creature doesn't acutally perform melee attacks but only acts on aggro

2020-10-24 17:28 UTC, ziang4891 commented on Database/Patches/2013-11-FowlPlay/9 WeenieDefaults/Creature/Unsorted/52305 Corrupted Gravestone.sql
> +     , (52305,  83,       2048) /* ActivationResponse - Emote */
ActivationResponse - Emote is not needed

2020-10-25 01:29 UTC, sLackeR-hub commented on Database/Patches/2013-11-FowlPlay/9 WeenieDefaults/Creature/Unsorted/52305 Corrupted Gravestone.sql
> +
Fixed. Per Frozen Crystal.

2020-10-25 01:29 UTC, sLackeR-hub commented on Database/Patches/2013-11-FowlPlay/9 WeenieDefaults/Creature/Unsorted/52305 Corrupted Gravestone.sql
> +     , (52305,  83,       2048) /* ActivationResponse - Emote */
Removed

2020-10-26 04:21 UTC, ziang4891 submitted a review, later dismissed

2020-10-27 19:41 UTC, DridsGhost submitted a review, later dismissed

2020-10-28 05:26 UTC, merged