Added Pumpkin Casters
ACEmulator/ACE-World-16PY-Patches pull request #657
Opened 2020-10-05 01:37 UTC by sLackeR-hub

**Added**
52190 - Original Version
52190 - Flaming Version
52192 - Glowing Version

PCAP captured them at 10% MeleeD Wikis have it at 20%

2020-10-07 01:18 UTC, ziang4891 requested changes
Missing ClothingBase, PaletteTemplate, and Shade properties

2020-10-07 21:05 UTC, DridsGhost requested changes

2020-10-07 21:05 UTC, DridsGhost commented on Database/Patches/2013-10-ShatteredMasks/9 WeenieDefaults/Caster/52190 Casting Jack o' Lantern.sql
> +     , (52190,   3,         78) /* PaletteTemplate - Olive */
Yotes says 76 - Orange on these.

2020-10-07 23:38 UTC, sLackeR-hub commented on Database/Patches/2013-10-ShatteredMasks/9 WeenieDefaults/Caster/52190 Casting Jack o' Lantern.sql
> +     , (52190,   3,         78) /* PaletteTemplate - Olive */
whoops

2020-10-09 13:49 UTC, ziang4891 approved these changes

2020-10-09 23:36 UTC, DridsGhost approved these changes

2020-10-10 19:10 UTC, merged