Mhoire Armory and Quests
ACEmulator/ACE-World-16PY-Patches pull request #672
Opened 2020-10-13 14:32 UTC by sLackeR-hub

**Created Mhoire Armory along with Quests**

**Added**
NPCs -
Jester

Creatures-
Corrupted Maiden
Spectral Dread
Forge Golem
Grave Rat
Wight Captain
Wight Blade Sorcerer
Rock Wall
Armory Door
West/North/East/South Armory Captains

Items -
Jester's Markers
Jester's Marbles 
Doors / Keys
Mhoire Forge Portal (Quest Restricted)

Quests - 
Jester's Lost Marbles
Jester's Markers
Spectral Weapons

2020-10-24 04:26 UTC, ziang4891 requested changes
Missing NpcLooksLikeObject on all of the objects in 2008-05-Introductions\9 WeenieDefaults\Creature\Unsorted

2020-10-24 04:26 UTC, ziang4891 commented on Database/Patches/2008-05-Introductions/8 QuestDefDB/JesterMarkerQuest.sql
> +
This file is duplicated in 2008-03-FoolishAmbition\8 QuestDefDB

2020-10-24 04:26 UTC, ziang4891 commented on Database/Patches/2008-05-Introductions/9 WeenieDefaults/Creature/Unsorted/37157 Door.sql
> +
Missing NpcLooksLikeObject

2020-10-25 01:46 UTC, sLackeR-hub commented on Database/Patches/2008-05-Introductions/9 WeenieDefaults/Creature/Unsorted/37157 Door.sql
> +
Fixed on all Unsorted.

2020-10-25 01:50 UTC, sLackeR-hub commented on Database/Patches/2008-05-Introductions/8 QuestDefDB/JesterMarkerQuest.sql
> +
Removed from Foolish Ambition.

2020-10-25 01:57 UTC, sLackeR-hub commented on Database/Patches/2008-03-FoolishAmbition/9 WeenieDefaults/Creature/Unsorted/37169 Master's Sentinel.sql
> +
Added.

2020-10-28 05:28 UTC, merged