Lunnum's Return (Black Skull of Xikma Quest)
ACEmulator/ACE-World-16PY-Patches pull request #675
Opened 2020-10-19 23:35 UTC by sLackeR-hub

**Added**

**NPC**
Fiun Layeel

**Portals**
Bookcase
Temple Entrance

**Items**
Fiun Crown
Lunnums Chest
Lunnums Token
Lunnums Chest
Doors/Keys
Blue Face Paint Recipe

**Creatures**
Afesse Sclavus
Illu Sclavus
Lunnum
Patrician Kilkitris/Phaerix
Storage Crate

**Quests**
Lunnum's Return

**Landblocks**
00EF
9EE8
536D

2020-10-24 17:18 UTC, ziang4891 requested changes

2020-10-24 17:18 UTC, ziang4891 commented on Database/Patches/2006-10-DanceOfTheDead/9 WeenieDefaults/Creature/Unsorted/87150 Storage Crate.sql
> +     , (87150, 9,     0,  0, 0, 0.85, False) /* Create nothing for ContainTreasure */;
Being that this mob is NoCorpse, a ContainTreasure is never going to work.  You will need to have a separate event generator that this crate activates on death and then deactivates on generation.

2020-10-25 15:12 UTC, sLackeR-hub commented on Database/Patches/2006-10-DanceOfTheDead/9 WeenieDefaults/Creature/Fiun/32595 Fiun Layeel.sql
> +
Fixed

2020-10-25 15:12 UTC, sLackeR-hub commented on Database/Patches/2006-10-DanceOfTheDead/9 WeenieDefaults/Portal/32811 Bookcase.sql
> +     , (32811,  53,        101) /* PlacementPosition - Resting */
Removed

2020-10-25 15:12 UTC, sLackeR-hub commented on Database/Patches/2006-10-DanceOfTheDead/9 WeenieDefaults/Portal/32811 Bookcase.sql
> +
Fixed.

2020-10-28 06:58 UTC, ziang4891 commented on Database/Patches/2006-10-DanceOfTheDead/9 WeenieDefaults/Creature/Fiun/32595 Fiun Layeel.sql
> +
Still not fixed

2020-10-29 06:25 UTC, ziang4891 approved these changes

2020-11-27 17:30 UTC, ziang4891 approved these changes

2020-12-03 00:31 UTC, merged