Update and rename 20980 Salvaged Alabaster.sql to 20980 Alabaster Sal…
ACEmulator/ACE-World-16PY-Patches pull request #810
Opened 2021-01-24 15:04 UTC by sapphire-knight

…vage.sql

Per PCAP and wikis, should be "Alabaster Salvage" not "Salvaged Alabaster"

http://ac.yotesfan.com/weenies/items/20980
https://asheron.fandom.com/wiki/Alabaster_Salvage
http://acpedia.org/wiki/Alabaster_Salvage

2021-01-24 16:49 UTC, ziang4891 approved these changes
All of the Salvage in this directory should probably be similarly updated

2021-02-02 05:01 UTC, LtRipley36706 requested changes

2021-02-02 05:01 UTC, LtRipley36706 commented on Database/Patches/2017-01-EndOfRetail/9 WeenieDefaults/SQL/CraftTool/TinkeringMaterial/20980 Alabaster Salvage.sql
> +VALUES (20980,   1, 'Alabaster Salvage') /* Name */
```suggestion
VALUES (20980,   1, 'Salvage') /* Name */
```

2021-02-02 05:01 UTC, LtRipley36706 commented on Database/Patches/2017-01-EndOfRetail/9 WeenieDefaults/SQL/CraftTool/TinkeringMaterial/20980 Alabaster Salvage.sql
> +VALUES (20980,   1, 'Alabaster Salvage') /* Name */
[PCAP has most Salvage named just that: Salvage](https://github.com/ACEmulator/ACE-PCAP-Dynamics-Exports/blob/master/Database/3-Core/9%20WeenieDefaults/SQL/CraftTool/TinkeringMaterial/20980%20Salvage%20(100).sql) Client and server do "cute" things to make it change the way it appears

2021-02-02 05:54 UTC, merged