visual fixes
ACEmulator/ACE-World-16PY-Patches pull request #973
Opened 2021-07-21 22:26 UTC by Fire-Chimp

visual fixes

2021-07-21 22:54 UTC, ziang4891 requested changes
Duplicated file with ''43495 Gregoria Gurog Destroyer.sql' :: no comma

2021-07-21 22:56 UTC, ziang4891 commented on Database/Patches/2010-11-FromDarknessLight/9 WeenieDefaults/Creature/Human/43804 Sir Donovan.sql
> +     , (@parent_id, 5, 49 /* AwardLevelProportionalXP */, 1, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0.19999999, NULL, NULL, NULL, NULL, NULL, NULL, NUL
Removes the XP gain settings

2021-07-21 23:00 UTC, ziang4891 requested changes
43847 Sir Learth.sql and 43988 Lady Daenerah.sql are already in 2011-03-HiddenInShadows, which will overwrite anything put in these two files in this PR

2021-07-21 23:38 UTC, Fire-Chimp commented
On these two that are in November, do I put them in November then?

Sent from my iPhone

> On Jul 21, 2021, at 6:00 PM, ziang4891 ***@***.***> wrote:
> 
> ﻿
> @ziang4891 requested changes on this pull request.
> 
> 43847 Sir Learth.sql and 43988 Lady Daenerah.sql are already in 2011-03-HiddenInShadows, which will overwrite anything put in these two files in this PR
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.

2021-07-21 23:53 UTC, ziang4891 commented
Yes, any changes should be applied against the ones in November patch folder

2021-07-22 00:23 UTC, Fire-Chimp commented
I had those in November 

Sent from my iPhone

> On Jul 21, 2021, at 6:00 PM, ziang4891 ***@***.***> wrote:
> 
> ﻿
> @ziang4891 requested changes on this pull request.
> 
> 43847 Sir Learth.sql and 43988 Lady Daenerah.sql are already in 2011-03-HiddenInShadows, which will overwrite anything put in these two files in this PR
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.

2021-07-22 00:24 UTC, Fire-Chimp commented
Oops never mind

Sent from my iPhone

> On Jul 21, 2021, at 6:00 PM, ziang4891 ***@***.***> wrote:
> 
> ﻿
> @ziang4891 requested changes on this pull request.
> 
> 43847 Sir Learth.sql and 43988 Lady Daenerah.sql are already in 2011-03-HiddenInShadows, which will overwrite anything put in these two files in this PR
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.

2021-07-25 16:39 UTC, ziang4891 requested changes

2021-07-25 16:39 UTC, ziang4891 commented on Database/Patches/2010-11-FromDarknessLight/9 WeenieDefaults/Creature/Human/43804 Sir Donovan.sql
> +     , (@parent_id, 5, 49 /* AwardLevelProportionalXP */, 1, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0.19999999, NULL, NULL, NULL, NULL, NULL, NULL, NUL
Change is still Null'ing the AwardLevelProportionalXP values

2021-07-25 16:39 UTC, ziang4891 commented on Database/Patches/2011-03-HiddenInShadows/9 WeenieDefaults/Creature/Human/43988 Lady Daenerah.sql
> +
Should be moved to the 2011-04-DarkDeliveries Patches subfolder

2021-07-25 21:18 UTC, Fire-Chimp commented
I hope I did it right

Sent from my iPhone

> On Jul 25, 2021, at 11:39 AM, ziang4891 ***@***.***> wrote:
> 
> ﻿
> @ziang4891 requested changes on this pull request.
> 
> In Database/Patches/2011-03-HiddenInShadows/9 WeenieDefaults/Creature/Human/43988 Lady Daenerah.sql:
> 
> > @@ -0,0 +1,191 @@
> +DELETE FROM `weenie` WHERE `class_Id` = 43988; 
> +
> Should be moved to the 2011-04-DarkDeliveries Patches subfolder
> 
> In Database/Patches/2010-11-FromDarknessLight/9 WeenieDefaults/Creature/Human/43804 Sir Donovan.sql:
> 
> > @@ -180,7 +166,7 @@ VALUES ***@***.***_id, 0, 12 /* TurnToTarget */, 0, 1, NULL, NULL, NULL, NULL, NULL
>       , ***@***.***_id, 2, 10 /* Tell */, 0, 1, NULL, 'You''ve done well. That crystal radiates a ton of geomantic power. The Master Bloodstone must''ve been very powerful.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
>       , ***@***.***_id, 3, 10 /* Tell */, 0, 1, NULL, 'Here, let''s see if we can put some of that power to work for you.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
>       , ***@***.***_id, 4, 18 /* DirectBroadcast */, 1.5, 1, NULL, 'Sir Donovan pulls out some salvaged supplies, and converts a section of the shard into a rather delicate looking wand.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
> -     , ***@***.***_id, 5, 49 /* AwardLevelProportionalXP */, 1, 1, NULL, NULL, NULL, 0, 280000000, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0.19999999, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
> +     , ***@***.***_id, 5, 49 /* AwardLevelProportionalXP */, 1, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0.19999999, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
> Change is still Null'ing the AwardLevelProportionalXP values
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.

2021-07-25 21:33 UTC, Fire-Chimp commented
I am kinda confused on sir Donovan. All I did was changes his underclothes. I did nothing to the awardlevelproportionaxp values.

Sent from my iPhone

> On Jul 25, 2021, at 4:18 PM, David Hastings ***@***.***> wrote:
> 
> ﻿I hope I did it right
> 
> Sent from my iPhone
> 
>>> On Jul 25, 2021, at 11:39 AM, ziang4891 ***@***.***> wrote:
>>> 
>> ﻿
>> @ziang4891 requested changes on this pull request.
>> 
>> In Database/Patches/2011-03-HiddenInShadows/9 WeenieDefaults/Creature/Human/43988 Lady Daenerah.sql:
>> 
>> > @@ -0,0 +1,191 @@
>> +DELETE FROM `weenie` WHERE `class_Id` = 43988; 
>> +
>> Should be moved to the 2011-04-DarkDeliveries Patches subfolder
>> 
>> In Database/Patches/2010-11-FromDarknessLight/9 WeenieDefaults/Creature/Human/43804 Sir Donovan.sql:
>> 
>> > @@ -180,7 +166,7 @@ VALUES ***@***.***_id, 0, 12 /* TurnToTarget */, 0, 1, NULL, NULL, NULL, NULL, NULL
>>       , ***@***.***_id, 2, 10 /* Tell */, 0, 1, NULL, 'You''ve done well. That crystal radiates a ton of geomantic power. The Master Bloodstone must''ve been very powerful.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
>>       , ***@***.***_id, 3, 10 /* Tell */, 0, 1, NULL, 'Here, let''s see if we can put some of that power to work for you.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
>>       , ***@***.***_id, 4, 18 /* DirectBroadcast */, 1.5, 1, NULL, 'Sir Donovan pulls out some salvaged supplies, and converts a section of the shard into a rather delicate looking wand.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
>> -     , ***@***.***_id, 5, 49 /* AwardLevelProportionalXP */, 1, 1, NULL, NULL, NULL, 0, 280000000, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0.19999999, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
>> +     , ***@***.***_id, 5, 49 /* AwardLevelProportionalXP */, 1, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0.19999999, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
>> Change is still Null'ing the AwardLevelProportionalXP values
>> 
>> —
>> You are receiving this because you authored the thread.
>> Reply to this email directly, view it on GitHub, or unsubscribe.

2021-07-25 22:03 UTC, Fire-Chimp commented on Database/Patches/2010-11-FromDarknessLight/9 WeenieDefaults/Creature/Human/43804 Sir Donovan.sql
> +     , (@parent_id, 5, 49 /* AwardLevelProportionalXP */, 1, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0.19999999, NULL, NULL, NULL, NULL, NULL, NULL, NUL
let me know if that didnt fix it.

2021-07-26 03:50 UTC, ziang4891 approved these changes

2021-07-26 03:59 UTC, merged